#!/bin/sh
#

if [ "$#" -ne "1" ]; then
	echo "Usage: skyhookuser <LOGIN>"
	exit 1;
fi

BASE=/home/$1/.ssh

# Comment the following if you dont match based
# on groups
GROUP=skyhook
groups $1 | grep $GROUP > /dev/null
if [ "$?" -ne "0" ]; then
	echo "User $1 is not part of group $GROUP"
	exit 1
fi

if [ ! -e $BASE/config  ]; then
	echo "No $BASE/config file found for the user $1"
	exit 1
fi

if [ ! -e $BASE/authorized_keys  ]; then
	echo "No $BASE/authorized_keys file found for the user"
	exit 1
fi

grep "Host SKYHOOK_TARGET" $BASE/config > /dev/null
if [ "$?" -ne "0" ]; then
	echo "$BASE/config MUST include Host SKYHOOK_TARGET"
	exit 1
fi

echo "Setting $BASE as immutable"
chattr -R +i $BASE

