#!/bin/sh
GROUP=skyhook
SKYHOOK_BASE=/usr/libexec/skyhook/

# check SSH_ORIGINAL_COMMAND
if [ -z $SSH_ORIGINAL_COMMAND ]; then
	echo "skyhook invoked outside of SSH"
	exit 1
fi

if [ "$SSH_ORIGINAL_COMMAND" -ne "skyhook" ]; then
	echo "This is a skyhook account, you need to configure your SSH"
	echo "client with the correct ProxyCommand"
	exit 2
fi

# check for $USER
if [ -z $USER ]; then
	echo "Internal error (3)"
	exit 3;
fi

# check if the user is part of the *skyhook* group
groups $1 | grep $GROUP > /dev/null
if [ "$?" -ne "0" ]; then
	echo "Your user is not allowed to puddle jump (4)"
	exit 4
fi

# check if hook is in place
HOOK=$SKYHOOK_BASE/$USER
if [ ! -e $HOOK  ]; then
	echo "Could not find a hook for this user (5)"
	exit 5
fi

$HOOK

